discourse_preset_topic_composer:
  discourse_preset_topic_composer_enabled:
    default: false
    client: true
  show_new_topic_button_only_on_categories:
    default: false
    client: true
  hide_unmatched_composer_presets:
    default: false
    client: true
  button_types:
    client: true
    default: >-
      [
        {
          "id": "NEW_QUESTION",
          "name": "New question",
          "description": "Ask a new question in selected category.",
          "icon": "question",
          "categoryId": 19,
          "tags": "question",
          "showTags": false,
          "access": "",
          "tagGroups": []
        },
        {
          "id": "NEW_SHOWCASE",
          "name": "New showcase",
          "description": "Share your case with community",
          "icon": "discourse-sparkles",
          "categoryId": 0,
          "tags": "showcase",
          "showTags": false,
          "access": "",
          "tagGroups": []
        },
        {
          "id": "NEW_COLLABORATION",
          "name": "New collaboration",
          "description": "Build, or find your team",
          "icon": "handshake-angle",
          "categoryId": 0,
          "tags": "collaboration",
          "showTags": false,
          "access": "",
          "tagGroups": []
        },
        {
          "id": "NEW_EVENT",
          "name": "New event",
          "description": "Share a public event",
          "icon": "far-calendar-plus",
          "categoryId": 0,
          "tags": "event",
          "showTags": false,
          "access": "",
          "tagGroups": []
        }
      ]
    json_schema: DiscoursePresetTopicComposer::SiteSettings::ButtonTypesJsonSchema
